version: '3.8'

services:
  angular-app:
    build: 
      context: .
      dockerfile: Dockerfile-angular
    ports:
      - "80:80"
    depends_on:
      - json-server

  json-server:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:80"
